name: pdfviewer
description: a simple pdf viewer created by Saksham
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_pdfview: ^1.4.0+1
  file_picker: ^10.1.5
  google_fonts: ^6.2.1
  dynamic_color: ^1.7.0
  pdf: ^3.11.3
  path_provider: ^2.1.5
  tabler_icons: ^2.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
